12

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -41,25 +41,25 @@ jobs:
       run: docker-compose -f "docker-compose.yaml" up -d --build
 
     - name: Check Cassandra readiness
-    run: |
-      echo "Checking Cassandra readiness..."
-      MAX_TRIES=20
-      COUNTER=0
-   
-      # This command will try to execute a simple CQL command. If Cassandra is not ready, it will fail.
-      # We will try MAX_TRIES times, waiting for 10 seconds between each try.
-      until docker exec cassandra1 cqlsh --debug cassandra1 9042 --execute="SELECT now() FROM system.local;" || [ $COUNTER -eq $MAX_TRIES ]; do
-        sleep 10
-        echo "Waiting for Cassandra to be ready... Try: $COUNTER"
-        ((COUNTER++))
-      done
-   
-      if [ $COUNTER -eq $MAX_TRIES ]; then
-        echo "Cassandra was not ready after $MAX_TRIES attempts. Exiting..."
-        exit 1
-      fi
-   
-      echo "Cassandra is ready!"      
+      run: |
+        echo "Checking Cassandra readiness..."
+        MAX_TRIES=20
+        COUNTER=0
+    
+        # This command will try to execute a simple CQL command. If Cassandra is not ready, it will fail.
+        # We will try MAX_TRIES times, waiting for 10 seconds between each try.
+        until docker exec cassandra1 cqlsh --debug cassandra1 9042 --execute="SELECT now() FROM system.local;" || [ $COUNTER -eq $MAX_TRIES ]; do
+          sleep 10
+          echo "Waiting for Cassandra to be ready... Try: $COUNTER"
+          ((COUNTER++))
+        done
+    
+        if [ $COUNTER -eq $MAX_TRIES ]; then
+          echo "Cassandra was not ready after $MAX_TRIES attempts. Exiting..."
+          exit 1
+        fi
+    
+        echo "Cassandra is ready!"      
 
     # - name: Wait for Cassandra
     #   run: |
